services:
  - type: web
    name: project-mahiru-backend
    env: docker
    rootDir: backend
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: GNANI_API_KEY
        sync: false
      - key: ALCHEMYST_AI_API_KEY
        sync: false
